/**
 * RAG chunk: Item generation.
 * Injected when the user asks about generating, editing, or saving item definitions.
 */
export const KEYWORDS = [
    'item', 'items', 'item definition', 'generate item', 'create item', 'edit item',
    'modify item', 'rarity', 'common', 'uncommon', 'rare', 'epic', 'legendary',
    'attributes', 'weapon', 'armor', 'equipment', 'item_generation', 'item_modify',
    'tạo item', 'vật phẩm', 'định nghĩa item', 'chỉnh sửa item', 'độ hiếm',
];
export const INTENT_TYPES = ['item_generation', 'item_modify', 'generator_item_creating'];
export const DOC = `
# Item Generation

## What Is an Item Definition?
An item definition (ItemDefinition) is a template for a type of item in the game. It is NOT an instance in a player's inventory � it is the blueprint that defines the item's properties.

Fields generated by AI:
- **name** � item display name
- **rarity** � one of: common, uncommon, rare, epic, legendary
- **description** � flavor text / tooltip
- **attributes** � key-value numeric stats (e.g. `{"attack": 50, "defense": 20}`)

## How to Generate Items
1. Open or create a conversation for your game.
2. Type a prompt like: "Generate 10 weapons for a Dark Knight class with medieval fantasy theme".
3. The system detects `item_generation` intent and streams results.
4. Review the generated items in the conversation panel.
5. Click "Create Records" to save them as real ItemDefinition records in the game.

## Linking References for Better Results
Before generating, link existing content to the conversation:
- **Lore entries** � the AI names items consistent with the lore world.
- **Existing item definitions** � the AI scales attributes relative to existing items and avoids duplicates.

## Editing Generated Items
After generation, you can ask to modify items:
- "Make the sword's attack attribute 20% higher"
- "Change the rarity of the first dagger to epic"
- "Rename the shield to 'Aegis of the Fallen'"
This triggers `item_modify` intent and updates the accumulated items in the conversation.

## Rarity Scale
| Rarity | Typical Use |
|---|---|
| common | Starter / filler items |
| uncommon | Slightly better, early-mid game |
| rare | Notable drops, mid-game |
| epic | Hard to get, high-end |
| legendary | Pinnacle items, very rare |

## Generator Items (`generator_item_creating`)
Some games use generator templates. When linked to a generator, the AI creates items following the generator's parameter constraints.
`;
